on:
  workflow_call:
    
name: go test the official images generator
jobs:
  go-test:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v6.0.2
      with:
        fetch-depth: 0
    - name: Set up Go based on go.mod
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: docker-official-images/go.mod
    - name: Run tests
      run: go test ./... -coverprofile=coverage.out
      working-directory: docker-official-images/
    - name: Upload coverage file
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: docker-official-images-coverage-${{ github.sha }}
        path: docker-official-images/coverage.out
        retention-days: 1
